accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

from . import views

app_name = 'accounts'


urlpatterns = [
    path('', views.about, name='about'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('login_required/', LoginView.as_view(template_name='accounts/login_required.html'), name='login_required'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('register/', views.register, name='register'),
    path('register/success/', views.register_success, name='register_success'),
    path('profile/', views.view_profile, name='view_profile'),
    # path('profile/<int:other_user_id>/', views.view_profile_other, name='view_profile_other'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    path('profile/create_avatar/', views.edit_avatar, name='create_avatar'),
    path('profile/delete_avatar/<int:avatar_id>', views.edit_avatar, name='delete_avatar'),
    path('profile/edit_avatar/<int:avatar_id>', views.edit_avatar, name='edit_avatar'),

    path('profile/view_avatar/<int:avatar_id>', views.ViewAvatar.as_view()
         , name='view_avatar'),

    path('profile/pdf_charsheets/', views.ViewPDFChars.as_view(), name='pdf_charsheets'),

    path('profile/password/', views.change_password, name='password'),
    path('profile/password/success/', views.change_password_success, name='password_success'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                   success_url='done/',
                                   email_template_name='accounts/password_reset_email.html'
                                   ),
         name='password_reset'
         ),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(success_url='../../../complete/',
                                          template_name='accounts/password_reset_confirm.html',
                                          ),
         name='password_reset_confirm'
         ),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'
         )

]

gendice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views

app_name = 'gendice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         views.BadRoom.as_view(template_name="gendice/bad_room_gen.html"), name='bad_room'),

    path('enter_with_passcode/',
         views.HubView.as_view(template_name="gendice/enter_with_passcode_gen.html"), name='enter_passcode_gen'),
    path('enter_with_passcode/<int:swroom_id>/',
         views.HubView.as_view(template_name="gendice/enter_with_passcode_gen.html"), name='enter_passcode_room'),
    path('confluence/',
         views.HubView.as_view(template_name="gendice/hub_confluence.html"), name='confluence'),
    path('switch_avatar/room/<int:swroom_id>/',
         views.HubView.as_view(template_name="gendice/replace_avatar_gen.html"), name='switch_avatar_room_gen'),

    path('room/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="gendice/room_gen.html"), name='genroom'),
    path('room/<int:swroom_id>/info',
         views.SWRoomViews.as_view(template_name="gendice/room_gen_info.html"), name='genroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.SWRoomViews.as_view(template_name="gendice/room_gen_info_player.html"), name='genroom_player_info'),

    path('room_nc/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="gendice/room_gen_nc.html"), name='genroom_nc'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         views.DirectLink.as_view(template_name="swdice/room_gen_link_direct"), name='room_gen_link_direct'),

    path('makeroom/',
         views.MakeDiceRoom.as_view(template_name='gendice/room_gen_make.html'), name='make_genroom'),
    path('change_passcode/<int:swroom_id>/',
         views.MakeDiceRoom.as_view(template_name='gendice/room_gen_passcode_change.html'), name='change_passcode_gen'),

    path('404', views.error_gen, name='404'),
]

handler404 = views.error_gen

polydice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views
from swdice import views as sw_views

app_name = 'polydice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         sw_views.BadRoom.as_view(template_name="polydice/bad_room_poly.html"), name='bad_room'),

    path('enter_with_passcode/',
         sw_views.HubView.as_view(template_name="polydice/enter_with_passcode_poly.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         sw_views.HubView.as_view(template_name="polydice/enter_with_passcode_poly.html"), name='enter_passcode_room'),
    path('dungeon/',
         sw_views.HubView.as_view(template_name="polydice/hub_dungeon.html"), name='dungeon'),
    path('switch_avatar/',
         sw_views.HubView.as_view(template_name="polydice/replace_avatar_poly.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         sw_views.HubView.as_view(template_name="polydice/replace_avatar_poly.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.PolyRoomViews.as_view(template_name="polydice/room_poly.html"), name='polyroom'),
    path('room/<int:swroom_id>/info',
         views.PolyRoomViews.as_view(template_name="polydice/room_poly_info.html"), name='polyroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.PolyRoomViews.as_view(template_name="polydice/room_poly_info_player.html"), name='polyroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         sw_views.DirectLink.as_view(template_name="swdice/room_poly_link_direct"), name='room_poly_link_direct'),

    path('makeroom/',
         sw_views.MakeDiceRoom.as_view(template_name='polydice/room_poly_make.html'), name='make_polyroom'),
    path('change_passcode/<int:swroom_id>/',
         sw_views.MakeDiceRoom.as_view(template_name='polydice/room_poly_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

swdice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views

app_name = 'swdice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         views.BadRoom.as_view(template_name="swdice/bad_room.html"), name='bad_room'),

    path('enter_with_passcode/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode_room'),
    path('dockingbay/',
         views.HubView.as_view(template_name="swdice/hub_dockingbay.html"), name='dockingbay'),
    path('switch_avatar/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="swdice/room_sw.html"), name='swroom'),
    path('room/<int:swroom_id>/info',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info.html"), name='swroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info_player.html"), name='swroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         views.DirectLink.as_view(template_name="swdice/room_sw_link_direct"), name='room_sw_link_direct'),

    path('makeroom/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_make.html'), name='make_swroom'),
    path('change_passcode/<int:swroom_id>/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

vanlevy/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views


app_name = 'vanlevy'

urlpatterns = [
    path('', views.vl_home_view, name='blank'),
    path('home/', views.vl_home_view, name='home'),
    path('about/', views.vl_about_view, name='vl_about'),
    path('resources/', views.vl_resources_view, name='resources'),
    path('cool-stuff/', views.vl_cool_stuff_view, name='cool_stuff'),
    path('dice-rollers/', views.vl_dice_rollers_view, name='dice_rollers'),
    path('portal/', views.personal_portal, name='portal'),
    path('terms/', views.vl_terms_view, name='terms'),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('404/', views.vl_error, name='404'),
    path('kobolds/', views.kobolds_about_view, name='kobolds_about'),
    path('kobolds/terms/', views.kobolds_terms_view, name='kobolds_terms'),
    path('kobolds/privacy/', views.kobolds_privacy_view, name='kobolds_privacy'),
]

handler404 = views.vl_error

gendice/models.py
from django.db import models
from accounts.models import VanLevyUser, Avatar, BOOL_CHOICES


class GenCharSheet(models.Model):
    user = models.ForeignKey(VanLevyUser, on_delete=models.CASCADE)
    char_name = models.CharField(max_length=200, default='', blank=True)
    char_description = models.CharField(max_length=500, default='', blank=True)
    char_url_image = models.URLField(max_length=300, blank=True, default='')
    created_on = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(choices=BOOL_CHOICES, default=False)

gendice/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.views.generic import FormView, TemplateView
from django.views.generic.edit import FormMixin

from swdice.models import SWRoomToUser, SWRoomChat, SWRoom, SWRoomDestiny, SWDicePool
from swdice.forms import Make_SW_Room, Enter_SW_Room, Enter_SW_Direct, SW_Room_Chat_Form, SW_Dice_Roll
from swdice.dice import *
from swdice.views import *
from accounts.models import VanLevyUser, Avatar
import datetime


def about(request):
    template_name = 'gendice/about_gendiceroller.html'
    return render(request, template_name)


def error_gen(request):
    template_name = '404_gen.html'
    return render(request, template_name)

gendice/templates/gendice/genroom_info.html
{% extends 'gendice/genroom.html' %}

{% block head %}
    <meta charset="UTF-8">
    <title>Gen Room Info</title>
{% endblock %}

{% block brand %}
{% load static %}
    <a class="navbar-brand" href="{% url 'vanlevy:home' %}">
        <img src="{% static '/vanlevy/IconReverse_32.png' %}" alt="Van Levy Icon" height="32" width="32">
    </a>
<span class="d-inline-block text-truncate" style="max-width: 700px; color:white; font-size: 150%; margin-right: 10px;">
    {{room.name}}
</span>
<a class="navbar-brand" style="color:white;" href="{% url 'gendice:confluence' %}">
    <img src="{% static '/gendice/Genesys_32.png' %}" alt="SW Dice Roller" height="32" width="32">
    {% block subtitle %}{% endblock %}
</a>
<span class="d-inline-block" style="color:white; font-size: 150%;"> Info Page </span>
{% endblock %}

{% block other_navbar_right %}
{% endblock %}

{% load static %}

{% block user_table %}
<div class="container" id="current_users">
    <h5>Player Information Table</h5>
    <table id="users_table" style="100%">
        <tr>
            <th style="width:80px">User <br>Image</th>
            <th style="width:300px">&nbsp<br>Playing as</th>
            <th style="width:80px">Avatar <br>Image</th>
            <th style="width:80px">&nbsp<br>Role</th>
            {% if player_is_gm %}
            <th style="width:180px">Player <br>Info</th>
            {% endif %}
        </tr>
        {% for player in users_in_room %}
        {% if not player.banned or player_is_gm %}
        <tr>
            <td>
                {% if player.user_id.userprofile.user_url_image %}
                    <img src="{{ player.user_id.userprofile.user_url_image }}" width="40">
                {% else %}
                    <em>no image</em>
                {% endif %}
            </td>
            <td>
                <strong>{{ player.user_id.username }}</strong> playing as:
                <strong>
                    {% if player.avatar_id %}{{ player.avatar_id.avatar_name }}{% else %}theirself{% endif %}
                </strong>
            </td>
            <td>
                {% if player.avatar_id %}
                    {% if player.avatar_id.avatar_url_image %}
                        <img src="{{ player.avatar_id.avatar_url_image }}" width="40">
                    {% else %}
                        <em>no image</em>
                    {% endif %}
                {% else %}
                    {% if player.user_id.userprofile.user_url_image %}
                        <img src="{{ player.user_id.userprofile.user_url_image }}" width="40">
                    {% else %}
                        <em>no image</em>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if player.banned %}<em>banned</em>
                {% elif player.game_master %}<strong>GM</strong>
                {% else %}Player
                {% endif %}
            </td>
            {% if player_is_gm %}
            <td>
                <a href="{% url 'gendice:genroom_player_info' room_number player.user_id_id%}">
                <button type="button" class="btn btn-info btn-sm btn-outline-info" name="Player_Info">
                    Player Info
                </button>
                </a>
            </td>
            {% endif %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</div>
{% endblock %}

{% block gm_stuff %}
{% if player_is_gm %}
    <div class="container-fluid" id="gm_message">
        <div class="row">
            <div class="col">
                <h5>GM-only Information:</h5>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-md-6">
                <h6>Room Details</h6>
                <ul style="margin-left: -15px; margin-top: -5px">
                    <li><strong>Created on:</strong> {{ room.created_on }}</li>
                    <li><strong>Created by:</strong> {{ room.created_by.username }}</li>
                    <li><strong>Direct Link:</strong>
                        <button type="button" style="padding: 0;margin-left: 10px;"
                                onclick="copyURL(link_{{room.id}})">
                          <img src="{% static '/vanlevy/copy_button_40_clear.png' %}" alt="info" width="20" height="20">
                        </button>
                        <span style="word-wrap: break-word;" id="link_{{room.id}}">
                            www.vanlevy.com{% url 'gendice:genroom' room_number %}direct/{% if room.open_to_all %}open{% else %}{{ room.passcode}}{% endif %}
                        </span>
                    </li>
                    <li><strong>Room ID:</strong> <u>{{room.id}}</u></li>
                    {% if not room.open_to_all %}
                    <li><strong>Passcode:</strong>
                        {% if room.passcode %}
                            "{{ room.passcode }}"
                        {% else %}
                            this room's passcode has been left <em>blank</em>.
                        {% endif %}
                    </li>
                    {% else %}
                    <li>This room is <strong>open to all</strong></li>
                    {% endif %}
                </ul>
                {% if not room.disabled %}
                <a href="{% url 'gendice:change_passcode_gen' room_number %}">
                  <button type="button" class="btn btn-sm btn-outline-info" id="changePasscode"
                        style="margin-right: 15px;">
                    {% if not room.open_to_all %}
                        Change Passcode
                    {% else %}
                        Add Passcode
                    {% endif %}
                    <strong>&#12299</strong>
                  </button>
                </a>
                {% endif %}
            </div>
            <div class="col-md-6">
                {% if room.disabled %}
                <h5><span style="color: darkred;">This room has been <strong>archived</strong>.</span></h5>
                <p>
                    No rolls or chats can be made in this room. On the Docking Bay page, this room is only visible on the
                    Archived Rooms tab.
                </p>
                {% else %}
                <p>
                    As GM, you can choose to <em>archive</em> this room.<br>
                    Once a room has been <em>archived</em>, players will not be able to make any more rolls or chats, and
                    the room will only be visible on the Archived Rooms tab on the Docking Bay page.
                </p>
                {% endif %}
                <div class="row no-gutters" id="disable_button" style="padding: 0px 3px">
                    <div class="col-sm-3">
                      {% if room.disabled %}
                        <button type="button" class="btn btn-sm btn-outline-warning" id="restore"
                                onclick="showRestore()">
                        Restore Room?
                        </button>
                        <button type="button" class="btn btn-sm btn-outline-warning" id="cancel_restore"
                                style="display:none" onclick="hideRestore()">
                        Cancel
                        </button>
                      {% else %}
                        <button type="button" class="btn btn-sm btn-outline-danger" id="disable"
                                onclick="showDisable()">
                        Archive Room?
                        </button>
                        <button type="button" class="btn btn-sm btn-outline-danger" id="cancel_disable"
                                style="display:none" onclick="hideDisable()">
                        Cancel
                        </button>
                      {% endif %} <!--archive/restore button -->
                    </div>
                    <div class="col-sm-9">
                        <div class="container-fluid" id="are_you_sure" style="display: none;">
                            {% if room.disabled %}
                                Are you sure you want to RESTORE this room?
                                <form id="restore_form" method="POST">
                                {% csrf_token %}
                                    <button type="submit" class="btn btn-warning" name="restore_real">
                                        <strong>Yes. RESTORE this room.</strong>
                                    </button>
                                </form>
                            {% else %}
                                Are you sure you want to ARCHIVE this room?
                                <form id="archive_form" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger" name="archive_real">
                                        <strong>Yes. ARCHIVE this room..</strong>
                                    </button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

{% block room_header %}
<div class="container-fluid" style="background-color: #B5D4EF">
    <h4>This page does not automatically update.</h4>
    <p>You must manually refresh to see changes to destiny, new rolls, or new chats.</p>
    <p>
        However, this page loads <em>all</em> actions and chats, while the main page shows only the 100 most
        recent actions and 100 most recent chats.
    </p>
    <a href="{% url 'gendice:genroom' room_number %}">
    <button type="button" class="btn btn-info align-right" name="back to page">
        <strong>&#12298</strong> Back to Live Page
    </button>
    </a>
</div>
{% endblock %}

{% block form_inputs %}
<!-- remove inputs, destiny, and standard user information space -->
{% endblock %}

{% block alt_destiny %}
    <div class="container-fluid" id="destiny_area">
        <h5>Current Destiny</h5>
        <table id="destiny_table">
            <tr>
                <td>
                    <span class="container-fluid" id="destiny_box">
                    {% if dark_pips == 0  and light_pips == 0 %}
                    There are no Destiny Points
                    {% endif %}
                    {% for i in dark_pips|get_range %}
                        <img src="{% static 'swdice/Pips/black.png' %}" width="40" title="Use Dark">
                    {% endfor %}
                    {% for i in light_pips|get_range %}
                        <img src="{% static 'swdice/Pips/white.png' %}" width="40" title="Use Light">
                    {% endfor %}
                    </span>
                </td>
            </tr>
        </table>
    </div>
{% endblock %}
{% block actions_header %}
<hr>
<h5>Actions</h5>
{% endblock %}

{% block alt_chat_header %}
<hr>
<h5>Chats</h5>
{% endblock %}

{% block glossary %}
<!-- hide glossary -->
{% endblock%}

<!-- include block chat_log -->


{% block page_scripts %}
<script>
function showRestore() {
    document.getElementById('restore').style.display='none';
    document.getElementById('cancel_restore').style.display='block';
    document.getElementById('are_you_sure').style.display='block';
}
function hideRestore() {
    document.getElementById('restore').style.display='block';
    document.getElementById('cancel_restore').style.display='none';
    document.getElementById('are_you_sure').style.display='none';
}
function showDisable() {
    document.getElementById('disable').style.display='none';
    document.getElementById('cancel_disable').style.display='block';
    document.getElementById('are_you_sure').style.display='block';
}
function hideDisable() {
    document.getElementById('disable').style.display='block';
    document.getElementById('cancel_disable').style.display='none';
    document.getElementById('are_you_sure').style.display='none';
}
function copyTextToClipboard(text) {
  var textArea = document.createElement("textarea");

  // Place in top-left corner of screen regardless of scroll position.
  textArea.style.position = 'fixed';
  textArea.style.top = 0;
  textArea.style.left = 0;

  // Ensure it has a small width & height. Setting to 1px / 1em doesn't work as this gives a negative w/h on some browsers.
  textArea.style.width = '2em';
  textArea.style.height = '2em';

  // We don't need padding, reducing the size if it does flash render.
  textArea.style.padding = 0;

  // Clean up any borders.
  textArea.style.border = 'none';
  textArea.style.outline = 'none';
  textArea.style.boxShadow = 'none';

  // Avoid flash of white box if rendered for any reason.
  textArea.style.background = 'transparent';

  textArea.value = text;

  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();

  try {
    var successful = document.execCommand('copy');
    var msg = successful ? 'successful' : 'unsuccessful';
    console.log('Copying text command was ' + msg);
  } catch (err) {
    console.log('Oops, unable to copy');
  }

  document.body.removeChild(textArea);
}

function copyURL(element){
    console.log(element.innerText);
    var copyText = element.innerText;
    copyTextToClipboard(copyText)
    var msg = (copyText).concat(" copied to clipboard.")
    alert(msg);
}
</script>
{% endblock %}

gendice/templates/gendice/replace_avatar_gen.html
{% extends 'gen_base.html' %}

{% block head %}
    <meta charset="UTF-8">
    <title>Switch Avatar</title>
{% endblock %}

{% block subtitle %} Switch Avatar{% endblock %}

{% block body %}
<div class="container">
    <div class="container">
        <div class="row">
            <div class="col-9">
                <br>
                <h3>You currently are signed in as {{ my_avatars_list|get_item:room_id }}</h3>
                <h4>Select the avatar you wish to use in room
                    {% for room in my_rooms_list %}
                    {% if room.id == room_id %}
                    {{ room.name }}
                    {% endif %}
                    {% endfor %}.  </h4>
                <br>
                <form method="post">
                    {% csrf_token %}
                    <table>
                        <col width="240">
                        <col width="120">
                        <col width="240">
                        <tr style="display:none"> <!-- style="display:none" -->
                            <td align="right" valign="bottom"></td>
                            <td><strong>Room ID:</strong>
                            <br>
                                <!--{{form.room_number}}-->
                                <input id="room_number" type="number" name="room_number" value="{{ room_id }}" readonly>
                            <br>
                                {% if request.method.post %}
                                <strong>{{ form.room_number.errors }}</strong>
                                {% endif %}
                            </td>
                            <td>

                            </td>
                        </tr>
                        <tr><td></td><td><p></p></td></tr>
                        <tr style="display:none">  <!-- style="display:none" -->
                            <td align="right" valign="bottom">Leave this blank.</td>
                            <td><strong>Passcode:</strong>
                            <br>
                                <!--{{form.passcode}}-->
                                <input id="passcode" type="text" name="passcode" value="" readonly>
                            <br>
                                <strong>{{ form.passcode.errors }}</strong>
                            </td>
                            <td>

                            </td>
                        </tr>
                        <tr>
                            <td align="right" valign="bottom"><strong>Select your avatar.</strong></td>
                            <td><strong>Avatar Id:</strong>
                                <br>{{form.default_avatar}} <br>
                                <strong>{{ form.default_avatar.errors }}</strong>
                            </td>
                            <td>

                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td align="right"><p></p>
                                <button type="submit" class="btn btn-primary">Switch Avatar</button>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <p><br></p>
                                <a href="{% url 'accounts:create_avatar' %}">
                                <button type="button" class="btn btn-sm btn-outline-primary align-right">
                                    Create a new avatar
                                </button></a>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="col-3">
                <br>
                <h5>Avatars List</h5>
                <br>
                <strong>User:</strong>
                {% if user.userprofile.user_first_name %}
                    {{ user.userprofile.user_first_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
                <br>
                {% if user.userprofile.user_url_image %}
                    <img src="{{ user.userprofile.user_url_image }}" width="150">
                {% else %}
                    <em>no image.</em>
                {% endif %}
                <br>
                <hr>
                {% for avatar in my_avatar_objects %}
                    <strong>Avatar:</strong> {{ avatar.avatar_name }}<br>
                    {% if avatar.avatar_url_image %}
                        <img src="{{ avatar.avatar_url_image }}" width="150">
                    {% else %}
                        <em>no image.</em>
                    {% endif %}
                    <br>
                    <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}