gendice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views

app_name = 'gendice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         views.BadRoom.as_view(template_name="gendice/bad_room_gen.html"), name='bad_room'),

    path('enter_with_passcode/',
         views.HubView.as_view(template_name="gendice/enter_with_passcode_gen.html"), name='enter_passcode_gen'),
    path('enter_with_passcode/<int:swroom_id>/',
         views.HubView.as_view(template_name="gendice/enter_with_passcode_gen.html"), name='enter_passcode_room'),
    path('confluence/',
         views.HubView.as_view(template_name="gendice/hub_confluence.html"), name='confluence'),
    path('switch_avatar/room/<int:swroom_id>/',
         views.HubView.as_view(template_name="gendice/replace_avatar_gen.html"), name='switch_avatar_room_gen'),

    path('room/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="gendice/room_gen.html"), name='genroom'),
    path('room/<int:swroom_id>/info',
         views.SWRoomViews.as_view(template_name="gendice/room_gen_info.html"), name='genroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.SWRoomViews.as_view(template_name="gendice/room_gen_info_player.html"), name='genroom_player_info'),

    path('room_nc/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="gendice/room_gen_nc.html"), name='genroom_nc'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         views.DirectLink.as_view(template_name="swdice/room_gen_link_direct"), name='room_gen_link_direct'),

    path('makeroom/',
         views.MakeDiceRoom.as_view(template_name='gendice/room_gen_make.html'), name='make_genroom'),
    path('change_passcode/<int:swroom_id>/',
         views.MakeDiceRoom.as_view(template_name='gendice/room_gen_passcode_change.html'), name='change_passcode_gen'),

    path('404', views.error_gen, name='404'),
]

handler404 = views.error_gen

myzdice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views
from swdice import views as sw_views

app_name = 'myzdice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         sw_views.BadRoom.as_view(template_name="myzdice/bad_room.html"), name='bad_room'),

    path('enter_with_passcode/',
         sw_views.HubView.as_view(template_name="myzdice/enter_with_passcode.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         sw_views.HubView.as_view(template_name="myzdice/enter_with_passcode.html"), name='enter_passcode_room'),
    path('the_zone/',
         sw_views.HubView.as_view(template_name="myzdice/hub_the_zone.html"), name='the_zone'),
    path('switch_avatar/',
         sw_views.HubView.as_view(template_name="myzdice/replace_avatar.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         sw_views.HubView.as_view(template_name="myzdice/replace_avatar.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.MYZRoomViews.as_view(template_name="myzdice/room_myz.html"), name='myzroom'),
    path('room/<int:swroom_id>/info',
         views.MYZRoomViews.as_view(template_name="myzdice/room_myz_info.html"), name='myzroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.MYZRoomViews.as_view(template_name="myzdice/room_myz_info_player.html"), name='myzroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         sw_views.DirectLink.as_view(template_name="myzdice/room_myz_link_direct"), name='room_myz_link_direct'),

    path('makeroom/',
         sw_views.MakeDiceRoom.as_view(template_name='myzdice/room_myz_make.html'), name='make_myzroom'),
    path('change_passcode/<int:swroom_id>/',
         sw_views.MakeDiceRoom.as_view(template_name='myzdice/room_myz_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

polydice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views
from swdice import views as sw_views

app_name = 'polydice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         sw_views.BadRoom.as_view(template_name="polydice/bad_room_poly.html"), name='bad_room'),

    path('enter_with_passcode/',
         sw_views.HubView.as_view(template_name="polydice/enter_with_passcode_poly.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         sw_views.HubView.as_view(template_name="polydice/enter_with_passcode_poly.html"), name='enter_passcode_room'),
    path('dungeon/',
         sw_views.HubView.as_view(template_name="polydice/hub_dungeon.html"), name='dungeon'),
    path('switch_avatar/',
         sw_views.HubView.as_view(template_name="polydice/replace_avatar_poly.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         sw_views.HubView.as_view(template_name="polydice/replace_avatar_poly.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.PolyRoomViews.as_view(template_name="polydice/room_poly.html"), name='polyroom'),
    path('room/<int:swroom_id>/info',
         views.PolyRoomViews.as_view(template_name="polydice/room_poly_info.html"), name='polyroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.PolyRoomViews.as_view(template_name="polydice/room_poly_info_player.html"), name='polyroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         sw_views.DirectLink.as_view(template_name="swdice/room_poly_link_direct"), name='room_poly_link_direct'),

    path('makeroom/',
         sw_views.MakeDiceRoom.as_view(template_name='polydice/room_poly_make.html'), name='make_polyroom'),
    path('change_passcode/<int:swroom_id>/',
         sw_views.MakeDiceRoom.as_view(template_name='polydice/room_poly_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

swdice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views

app_name = 'swdice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         views.BadRoom.as_view(template_name="swdice/bad_room.html"), name='bad_room'),

    path('enter_with_passcode/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode_room'),
    path('dockingbay/',
         views.HubView.as_view(template_name="swdice/hub_dockingbay.html"), name='dockingbay'),
    path('switch_avatar/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="swdice/room_sw.html"), name='swroom'),
    path('room/<int:swroom_id>/info',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info.html"), name='swroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info_player.html"), name='swroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         views.DirectLink.as_view(template_name="swdice/room_sw_link_direct"), name='room_sw_link_direct'),

    path('makeroom/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_make.html'), name='make_swroom'),
    path('change_passcode/<int:swroom_id>/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

vanlevy/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views


app_name = 'vanlevy'

urlpatterns = [
    path('', views.vl_home_view, name='blank'),
    path('home/', views.vl_home_view, name='home'),
    path('about/', views.vl_about_view, name='vl_about'),
    path('resources/', views.vl_resources_view, name='resources'),
    path('cool-stuff/', views.vl_cool_stuff_view, name='cool_stuff'),
    path('dice-rollers/', views.vl_dice_rollers_view, name='dice_rollers'),
    path('portal/', views.personal_portal, name='portal'),
    path('terms/', views.vl_terms_view, name='terms'),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('404/', views.vl_error, name='404'),
    path('kobolds/', views.kobolds_about_view, name='kobolds_about'),
    path('kobolds/terms/', views.kobolds_terms_view, name='kobolds_terms'),
    path('kobolds/privacy/', views.kobolds_privacy_view, name='kobolds_privacy'),
]

handler404 = views.vl_error

vanlevy/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from django.template.defaulttags import register
from django.core.mail import send_mail, BadHeaderError

from django.conf import settings  # this is actually the settings of this project
from swdice.models import SWRoomToUser, SWRoom
from accounts.models import VanLevyUser, Avatar
from .forms import ContactForm, AREA_CHOICES, ISSUE_CHOICES

import datetime


# Filters for views
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@register.filter
def get_range(value):
    return range(value)


# classes and methods used by views
class TempRoom:
    def __init__(self, room_name, avatar, gm, id):
        self.room_name = room_name
        self.avatar = avatar
        self.gm = gm
        self.id = id


# views
def vl_home_view(request):
    if 'contact_message' in request.session:
        contact_message = request.session['contact_message']
        del request.session['contact_message']
        args = {'message': contact_message}
    else:
        args = {}
    template_name = 'vanlevy/vl_home.html'
    return render(request, template_name, args)


def vl_about_view(request):
    template_name = 'vanlevy/vl_about.html'
    return render(request, template_name)


def vl_resources_view(request):
    template_name = 'vanlevy/vl_resources.html'
    return render(request, template_name)


def vl_cool_stuff_view(request):
    template_name = 'vanlevy/vl_cool_stuff.html'
    return render(request, template_name)


def vl_dice_rollers_view(request):
    template_name = 'vanlevy/vl_dice_rollers.html'
    return render(request, template_name)


def vl_terms_view(request):
    template_name = 'vanlevy/vl_terms.html'
    return render(request, template_name)


def vl_error(request):
    template_name = '404_vl.html'
    return render(request, template_name)


def personal_portal(request):
    if 'requested_url' in request.session:
        requested_url = request.session['requested_url']
        del request.session['requested_url']
        return redirect(requested_url)

    current_user_id = request.user.id
    user_name = request.user.username
    my_avatars = Avatar.objects.filter(user_id=current_user_id, deleted=False).order_by('-id')
    if len(my_avatars) == 0:
        has_avatars = False
    else:
        has_avatars = True
    my_rooms_to_user_list = SWRoomToUser.objects.filter(user_id_id=current_user_id, banned=0).order_by(
        '-admitted')
    my_rooms_reversed_list = my_rooms_to_user_list[::-1]
    number_rooms = 5
    my_sw_rooms_list = []
    my_gen_rooms_list = []
    my_poly_rooms_list = []
    my_myz_rooms_list = []

    for room in my_rooms_reversed_list:
        this_room = SWRoom.objects.filter(pk=room.room_id_id)[0]
        room_name = (this_room.name[:38] + '..') if len(this_room.name) > 40 else this_room.name
        room_id = room.room_id_id
        if room.game_master:
            gm = "you"
        else:
            gm_rooms = SWRoomToUser.objects.filter(room_id=room.room_id, game_master=True)
            if gm_rooms:
                gm_id = gm_rooms[0].user_id
                gm_name = gm_id.username
                gm = gm_name
            else:
                gm = "no one"
        if room.default_avatar_is_user == 1:
            name_in_room = user_name
        else:
            try:
                name_in_room = Avatar.objects.filter(user_id=current_user_id, id=room.avatar_id_id)[0]
            except:
                name_in_room = user_name
        new_room = TempRoom(room_name, name_in_room, gm, room_id)
        if this_room.genesys:
            if len(my_gen_rooms_list) < number_rooms and not this_room.disabled:
                my_gen_rooms_list.append(new_room)
        elif this_room.polydice:
            if len(my_poly_rooms_list) < number_rooms and not this_room.disabled:
                my_poly_rooms_list.append(new_room)
        elif this_room.myzdice:
            if len(my_myz_rooms_list) < number_rooms and not this_room.disabled:
                my_myz_rooms_list.append(new_room)
        else:
            if len(my_sw_rooms_list) < number_rooms and not this_room.disabled:
                my_sw_rooms_list.append(new_room)

    outline_button = request.user.userprofile.user_first_name and request.user.userprofile.user_url_image

    template_name = 'vanlevy/vl_portal.html'
    args = {'user': request.user, 'my_sw_rooms_list': my_sw_rooms_list, 'my_gen_rooms_list': my_gen_rooms_list,
            'my_poly_rooms_list': my_poly_rooms_list, 'my_myz_rooms_list': my_myz_rooms_list,
            'my_avatars_list': my_avatars, 'has_avatars': has_avatars, 'number_rooms': number_rooms,
            'outline_button': outline_button}

    if 'contact_message' in request.session:
        contact_message = request.session['contact_message']
        del request.session['contact_message']
        args.update({'message': contact_message})
    return render(request, template_name, args)


class ContactPage(TemplateView, FormView):
    def get(self, request, *args, **kwargs):
        timestamp = datetime.datetime.now()
        if request.user.is_authenticated:
            initial_args = {'created_on': timestamp, 'user': request.user}
        else:
            initial_args = {'created_on': timestamp}
        contact_form = ContactForm(initial=initial_args)
        args = {'contact_form': contact_form}
        template_name = 'vanlevy/vl_contact.html'
        return render(request, template_name, args)

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        if request.user.is_authenticated:
            form = ContactForm(request.POST, instance=request.user)
            logged_in = True
            username = request.user.username
            user_id = request.user.id
            user_email = request.user.email
        else:
            form = ContactForm(request.POST)
            logged_in = False
            username = 'anonymous'
            user_id = 0
            user_email = ''

        timestamp = datetime.datetime.now()
        form.data['created_on'] = timestamp
        if request.user.is_authenticated:
            form.data['user_id'] = request.user.id
        if form.is_valid():
            form.save()
            area = str(AREA_CHOICES[int(form.cleaned_data['area_of_concern'])][1])
            issue = str(ISSUE_CHOICES[int(form.cleaned_data['issue_type'])][1])
            email = form.cleaned_data['given_email']
            message = form.cleaned_data['message']
            email_subject = 'VanLevy contact, re: ' + issue

            email_message = 'We have been sent a message from user: <' + username + '>. '
            if email:
                email_message += 'They have given their email as: <' + email + '> . '
            else:
                email_message += 'They have not given an email. '
            if logged_in:
                email_message += 'Their user information is: <' + username + '>; user id: <' + str(user_id) + \
                                 '>; user_email: <' + user_email + '> . '
            else:
                email_message += 'They were not logged in. '

            email_message += 'They have a concern about <' + area + '>. '
            email_message += 'Their issue is <' + issue + '>. '
            email_message += 'Their message is: ' + message
            email_recipient = ("contact@vanlevy.com",)

            try:
                send_mail(email_subject, email_message, settings.DEFAULT_FROM_EMAIL, email_recipient)
            except BadHeaderError:
                args = {'contact_form': form}
                template_name = 'vanlevy/vl_contact.html'
                return render(request, template_name, args)

            request.session['contact_message'] = "Message successfully sent."
            if request.user.is_authenticated:
                return redirect('vanlevy:portal')
            else:
                return redirect('vanlevy:home')
        else:
            args = {'contact_form': form}
            template_name = 'vanlevy/vl_contact.html'
            return render(request, template_name, args)


def kobolds_about_view(request):
    template_name = 'kobolds/kobolds_about.html'
    return render(request, template_name)


def kobolds_terms_view(request):
    template_name = 'kobolds/kobolds_terms.html'
    return render(request, template_name)


def kobolds_privacy_view(request):
    template_name = 'kobolds/kobolds_privacy.html'
    return render(request, template_name)

vanlevy/templates/vanlevy/vl_contact.html
{% extends 'vl_base.html' %}
{% load static %}
{% block brand %}
  <h3>
    <a class="navbar-brand" href="{% url 'vanlevy:home' %}">
      <img src="{% static '/vanlevy/images/IconReverse_40.png' %}" alt="Van Levy Icon"  height="40" width="40">
        Van Levy
    </a>
    <a class="navbar-brand">
      <span style="color: white; margin-left: -18px;"> - Contact Us</span>
    </a>
  </h3>
{% endblock %}
{% block bottom_dice %}
{% endblock %}
{% block bottom_resources %}
{% endblock %}
{% block bottom_links %}
{% endblock %}

{% block head %}
<meta charset="UTF-8">
<title>VanLevy Contact Us</title>

{% endblock %}

{% block body %}
<div class="container">
  <br>
  <div class="row">
    <div class="col" style="text-align: center;">
      <h2>Contact someone at www.VanLevy.com</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2 col-12"></div>
    <div class="col-lg-8">
      <p style="font-size: 0.80em;">
        Please fill out this form to send us your thoughts, comments, questions, queries, or quantities... of money.
        The kobolds that bring us these messages are specially trained to bring us offers of money quickly.
        For all other topics, they've been known to get ... distracted.  I wouldn't expect too much, if I were you.
      </p>
    </div>
    <div class="col-lg-2 col-12"></div>
  </div>

  <div class="row">
    <div class="col-lg-2 col-12"></div>
    <div class="col-lg-8">
      <form method="post"  autocomplete="off">
      {% csrf_token %}
        <div class="row">
          <div class="col-8">
            <p>
              Is there a part of the website you wanted to talk about?<br>
              {{ contact_form.area_of_concern }}<br>
            </p>
          </div>
          <div class="col-4">
            {% for error in contact_form.area_of_concern.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="row">
          <div class="col-8">
           <p>
             Is there an issue you wanted to tell us about?<br>
             {{ contact_form.issue_type }}<br>
           </p>
          </div>
          <div class="col-4">
            {% for error in contact_form.issue_type.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          </div>
        </div>

        <p>
          Message<br>
          {{ contact_form.message }}<br>
        </p>
        <p>
          <em>optional:</em> If you want us to be able to contact you, please leave your email below.<br>
          {{ contact_form.given_email }}<br>
        </p>
        <p><br></p>
        {% if contact_form.errors %}
          {% for field in contact_form %}
            {% for error in field.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in contact_form.non_field_errors %}
            <div class="alert alert-warning alert-dismissible fade show">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endif %}
        <p>Once you've finished the form, click below,</p>
        <button type="button" id="fake_submit" class="btn btn-outline-success" style="display: inline;"
                onclick="switchButtons()">
          Finished
        </button>
        <span style="display: none; color: darkred" id="submit_message"><strong>
          Are you sure you want to send this message? Press that button over there. &#8594;
        </strong></span>
        <button type="submit" id="real_submit" class="btn btn-success btn-lg align-right" style="display: none;">
          SEND
        </button>
      </form>
      <div class="row" id="other_submit_message" style="display: none; text-align: right;">
        <div class="col" style="text-align: right;">
          <br>
          <p>
            Nothing happens 'til you hit that "SEND" button. &#8593;
            <br>Check your message; find that typo,
            <br>and click the button, already!
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-2 col-12"></div>
  </div>
</div>

<script>
function switchButtons() {
  document.getElementById('fake_submit').style.display='none';
  document.getElementById('real_submit').style.display='inline';
  document.getElementById('submit_message').style.display='inline';
  document.getElementById('other_submit_message').style.display='inline';
}
</script>

{% endblock %}


{% block page_scripts %}

{% endblock %}

vanlevy/templates/vanlevy/vl_dice_rollers.html
{% extends 'vl_base.html' %}
{% load static %}
{% block brand %}
  <h3>
    <a class="navbar-brand" href="{% url 'vanlevy:home' %}">
      <img src="{% static '/vanlevy/images/IconReverse_40.png' %}" alt="Van Levy Icon"  height="40" width="40">
        Van Levy
    </a>
    <a class="navbar-brand">
      <span style="color: white; margin-left: -18px;"> - Dice Rollers</span>
    </a>
  </h3>
{% endblock %}
{% block bottom_navbar_padding %}
  style="padding: 20px 0px 0px 0px"
{% endblock %}
{% block bottom_navbar_style %}
  style="bottom: 0; "
{% endblock %}
{% block bottom_dice %}
{% endblock %}
{% block bottom_terms %}
{% endblock %}

{% block head %}
    <meta charset="UTF-8">
    <title>Dice Rollers</title>
{% endblock %}

{% block body %}
<div class="container">
  <br>
  <div class="row">
    <div class="col-lg-6">
      <div class="card border-dark mb-3" style="background-color: #d6e9f9;">
        <div class="card-header">
          <h4 class="card-title" style="display: inline;">Star Wars</h4> - by Fantasy Flight Games
        </div>
        <div class="card-body"
             style="background-image: url({% static '/vanlevy/images/CardImageDroid.png' %});
                     background-repeat: no-repeat; background-color: #d6e9f9; background-position: 5% 25%;
                     background-size: 40%; min-height: 240px;">
          <div class="row no-gutters">
            <div class="col-6">
              <p class="card-text">
                This Dice Roller uses Fantasy Flight Game's Star Wars RPG system.
              </p>
              <p class="card-text">
                To learn more about the rules that the dice roller uses, see the
                  <a href="{% url 'swdice:about' %}">info page.</a>
                To learn more about the system, please visit
                  <a href="https://www.fantasyflightgames.com/en/starwarsrpg/">Fantasy Flight Games</a>.
                </p>
            </div>
            <div class="col-6">
              <img src="{% static '/vanlevy/images/Dice_Edge_500_500.jpg' %}" alt="Edge Dice"
                   class="align-right dice-image">
            </div>
          </div>
        </div>
        <div class="card-footer">
          {% if user.is_authenticated %}
            <a href="{% url 'swdice:dockingbay' %}" class="btn btn-sm btn-primary">
              Docking Bay <strong>&#12299;</strong>
            </a>
          {% else %}
            <a href="{% url 'swdice:about' %}" class="btn btn-sm btn-primary">
              Info Page <strong>&#12299;</strong>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card border-dark mb-3" style="background-color: #D7D9F4;">
        <div class="card-header">
          <h4 class="card-title" style="display: inline;">Polyhedral</h4> - e.g. for D20 games
        </div>
        <div class="card-body"
             style="background-image: url({% static '/vanlevy/images/d20_reverse.png' %});
             background-repeat: no-repeat; background-color: #D7D9F4; background-position: 5% 25%;
             background-size: 40%; min-height: 240px;">
          <div class="row no-gutters">
            <div class="col-6">
              <p class="card-text">
                This Dice Roller uses basic Polyhedral Dice; d4, d6, d8, d10, d12, 20, d100, & d#.
              </p>
              <p class="card-text">
                To learn more about this dice roller, please visit the
                <a href="{% url 'polydice:about' %}">info page</a>.
                To learn more about game systems that use these dice, feel free to start at
                <a href="http://www.d20srd.org/index.htm">d20 SRD</a>.
              </p>
            </div>
            <div class="col-6">
              <img src="{% static '/vanlevy/images/Dice_Poly_500_500.jpg' %}" alt="Polyhedral Dice"
                   class="align-right dice-image">
            </div>
          </div>
        </div>
        <div class="card-footer">
          {% if user.is_authenticated %}
            <a href="{% url 'polydice:dungeon' %}" class="btn btn-sm btn-primary">
              The Dungeon <strong>&#12299;</strong>
            </a>
          {% else %}
            <a href="{% url 'polydice:about' %}" class="btn btn-sm btn-primary">
              Info Page <strong>&#12299;</strong>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="card border-dark mb-3" style="background-color: #fdecd9;">
        <div class="card-header">
          <h4 class="card-title" style="display: inline;">Genesys</h4> - by Fantasy Flight Games
        </div>
        <div class="card-body"
             style="background-image: url({% static '/vanlevy/images/Genesys_reverse.png' %});
             background-repeat: no-repeat; background-color: #fdecd9; background-position: 5% 25%;
             background-size: 40%; min-height: 240px;">
          <div class="row no-gutters">
            <div class="col-6">
              <p class="card-text">
                This Dice Roller uses Fantasy Flight Game's Genesys RPG system.
              </p>
              <p class="card-text">
                To learn more about the rules that the dice roller uses, see the
                  <a href="{% url 'gendice:about' %}">info page.</a>
                To learn more about the system, please visit
                  <a href="https://www.fantasyflightgames.com/en/products/genesys/">Fantasy Flight Games</a>.
              </p>
            </div>
            <div class="col-6">
              <img src="{% static '/vanlevy/images/Dice_Gen_500_500.jpg' %}" alt="Genesys Dice"
                   class="align-right dice-image">
            </div>
          </div>
        </div>
        <div class="card-footer">
          {% if user.is_authenticated %}
            <a href="{% url 'gendice:confluence' %}" class="btn btn-sm btn-primary">
              Confluence <strong>&#12299;</strong>
            </a>
          {% else %}
            <a href="{% url 'gendice:about' %}" class="btn btn-sm btn-primary">
              Info Page <strong>&#12299;</strong>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card border-dark mb-3" style="background-color: #F8EEC6;">
        <div class="card-header">
          <h4 class="card-title" style="display: inline;">Mutant Year Zero</h4> - by M&omacr;diphi&uuml;s
        </div>
        <div class="card-body"
             style="background-image: url({% static '/vanlevy/images/MutantYearZero_pale_200_2.png' %});
             background-repeat: no-repeat; background-color: #F8EEC6; background-position: 5% 25%;
             background-size: 40%; min-height: 240px;">
          <div class="row no-gutters">
            <div class="col-6">
              <p class="card-text">
                This Dice Roller uses M&omacr;diphi&uuml;s's Mutant Year Zero RPG system.
              </p>
              <p class="card-text">
                To learn more about the rules that the dice roller uses, see the
                  <a href="{% url 'myzdice:about' %}">info page.</a>
                To learn more about the system, please visit
                  <a href="https://www.modiphius.com/mutant.html">M&omacr;diphi&uuml;s</a>.
              </p>
            </div>
            <div class="col-6">
              <img src="{% static '/vanlevy/images/Dice_MYZ_500_500.jpg' %}" alt="Mutant Year Zero Dice"
              class="align-right dice-image">
            </div>
          </div>
        </div>
        <div class="card-footer">
          {% if user.is_authenticated %}
            <a href="{% url 'myzdice:the_zone' %}" class="btn btn-sm btn-primary">
              The Zone <strong>&#12299;</strong>
            </a>
          {% else %}
            <a href="{% url 'myzdice:about' %}" class="btn btn-sm btn-primary">
              Info Page <strong>&#12299;</strong>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}