accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

from . import views

app_name = 'accounts'


urlpatterns = [
    path('', views.about, name='about'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('login_required/', LoginView.as_view(template_name='accounts/login_required.html'), name='login_required'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('register/', views.register, name='register'),
    path('register/success/', views.register_success, name='register_success'),
    path('profile/', views.view_profile, name='view_profile'),
    # path('profile/<int:other_user_id>/', views.view_profile_other, name='view_profile_other'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    path('profile/create_avatar/', views.edit_avatar, name='create_avatar'),
    path('profile/delete_avatar/<int:avatar_id>', views.edit_avatar, name='delete_avatar'),
    path('profile/edit_avatar/<int:avatar_id>', views.edit_avatar, name='edit_avatar'),

    path('profile/view_avatar/<int:avatar_id>', views.ViewAvatar.as_view()
         , name='view_avatar'),

    path('profile/pdf_charsheets/', views.ViewPDFChars.as_view(), name='pdf_charsheets'),

    path('profile/password/', views.change_password, name='password'),
    path('profile/password/success/', views.change_password_success, name='password_success'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                   success_url='done/',
                                   email_template_name='accounts/password_reset_email.html'
                                   ),
         name='password_reset'
         ),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(success_url='../../../complete/',
                                          template_name='accounts/password_reset_confirm.html',
                                          ),
         name='password_reset_confirm'
         ),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'
         )

]

swdice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views

app_name = 'swdice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         views.BadRoom.as_view(template_name="swdice/bad_room.html"), name='bad_room'),

    path('enter_with_passcode/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode_room'),
    path('dockingbay/',
         views.HubView.as_view(template_name="swdice/hub_dockingbay.html"), name='dockingbay'),
    path('switch_avatar/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="swdice/room_sw.html"), name='swroom'),
    path('room/<int:swroom_id>/info',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info.html"), name='swroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info_player.html"), name='swroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         views.DirectLink.as_view(template_name="swdice/room_sw_link_direct"), name='room_sw_link_direct'),

    path('makeroom/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_make.html'), name='make_swroom'),
    path('change_passcode/<int:swroom_id>/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

vanlevy/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views


app_name = 'vanlevy'

urlpatterns = [
    path('', views.vl_home_view, name='blank'),
    path('home/', views.vl_home_view, name='home'),
    path('about/', views.vl_about_view, name='vl_about'),
    path('resources/', views.vl_resources_view, name='resources'),
    path('cool-stuff/', views.vl_cool_stuff_view, name='cool_stuff'),
    path('dice-rollers/', views.vl_dice_rollers_view, name='dice_rollers'),
    path('portal/', views.personal_portal, name='portal'),
    path('terms/', views.vl_terms_view, name='terms'),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('404/', views.vl_error, name='404'),
    path('kobolds/', views.kobolds_about_view, name='kobolds_about'),
    path('kobolds/terms/', views.kobolds_terms_view, name='kobolds_terms'),
    path('kobolds/privacy/', views.kobolds_privacy_view, name='kobolds_privacy'),
]

handler404 = views.vl_error

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as lazy

BOOL_CHOICES = [(True, 'Yes'), (False, 'No')]


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class VanLevyUser(AbstractUser):
    username = models.CharField(max_length=100,  unique=True)
    email = models.EmailField(lazy('email address'), unique=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']


class UserProfile(models.Model):
    user = models.OneToOneField(VanLevyUser, on_delete=models.CASCADE)
    user_bio = models.CharField(max_length=500, default='', blank=True)
    user_description = models.CharField(max_length=500, default='', blank=True)
    user_image = models.ImageField(upload_to='profile_image', blank=True)
    user_url_image = models.URLField(max_length=500, blank=True, default='')
    user_first_name = models.CharField(max_length=100, default='', blank=True)
    user_last_name = models.CharField(max_length=100, default='', blank=True)
    user_location = models.CharField(max_length=300, default='', blank=True)

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=VanLevyUser)


class PDFCharSheet(models.Model):
    user = models.ForeignKey(VanLevyUser, on_delete=models.CASCADE)
    pdf_url = models.URLField(max_length=300, blank=True, default='')
    pdf_name = models.CharField(max_length=200, default='', blank=True)
    archived = models.BooleanField(choices=BOOL_CHOICES, default=False)
    created_on = models.DateTimeField(blank=True, null=True)


class Avatar(models.Model):
    user = models.ForeignKey(VanLevyUser, on_delete=models.CASCADE)
    avatar_name = models.CharField(max_length=200, default='', blank=True)
    avatar_description = models.CharField(max_length=500, default='', blank=True)
    avatar_image = models.ImageField(upload_to='avatar_image', blank=True)
    avatar_url_image = models.URLField(max_length=300, blank=True, default='')
    created_on = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(choices=BOOL_CHOICES, default=False)
    use_char_sheet = models.PositiveSmallIntegerField(default=0)
    char_pdf = models.ForeignKey(PDFCharSheet, on_delete=models.CASCADE, blank=True, null=True)
    char_gen = models.ForeignKey('gendice.GenCharSheet', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.avatar_name == '':
            return self.user.username
        else:
            return self.avatar_name

accounts/forms.py
from django import forms
from accounts.models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model
from .models import Avatar, PDFCharSheet
from django.core.validators import EMPTY_VALUES


User = get_user_model()
BOOL_CHOICES = [(True, 'Yes'), (False, 'No')]


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'type': 'email', 'placeholder': 'Email'}))
    password1 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm'}))

    class Meta:
        model = User
        fields = ('username',
                  'email',
                  'password1',
                  'password2')

    def clean(self):
        if User.objects.filter(username=self.cleaned_data['username']).exists():
            error_msg_username = 'This username has already been assigned.'
            self.add_error('username', error_msg_username)
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            error_msg = "This email already has an account."
            self.add_error('email', error_msg)
        return self.cleaned_data

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'username', 'password')


class EditProfileForm(forms.ModelForm):
    user_bio = forms.CharField(required=False, label='User Bio',
                               widget=forms.Textarea(attrs={'rows': 6, 'cols': 55, 'id': 'about_me'})
                               )
    user_description = forms.CharField(required=False, label='Description',
                                       widget=forms.Textarea(attrs={'rows': 3, 'cols': 55, 'id': 'gaming_interests'})
                                       )
    user_image = forms.ImageField(required=False)
    user_url_image = forms.URLField(required=False, label='URL for Image',
                                    widget=forms.Textarea(
                                        attrs={'rows': 3, 'cols': 55, 'id': 'image_url',
                                               'placeholder':
                                                   'Images need to be valid URLs to a web-hosted image file.'}
                                        )
                                    )
    user_first_name = forms.CharField(required=False, label='First Name',
                                      widget=forms.TextInput(attrs={'id': 'first_name'})
                                      )
    user_last_name = forms.CharField(required=False, label='Last Name',
                                     widget=forms.TextInput(attrs={'id': 'last_name'})
                                     )
    user_location = forms.CharField(required=False, label='Description',
                                    widget=forms.Textarea(attrs={'rows': 1, 'cols': 55, 'id': 'location'})
                                    )

    class Meta:
        model = UserProfile
        fields = ('user_bio',
                  'user_description',
                  'user_image',
                  'user_url_image',
                  'user_first_name',
                  'user_last_name',
                  'user_location'
                  )


class EditAvatarForm(forms.ModelForm):
    avatar_name = forms.CharField(required=True, label='name',
                                  widget=forms.TextInput(attrs={'size': 35, 'id': 'name'})
                                  )
    avatar_description = forms.CharField(required=False, label='Description',
                                         widget=forms.Textarea(attrs={'rows': 5, 'cols': 55, 'id': 'description'})
                                         )
    avatar_image = forms.ImageField(required=False)
    avatar_url_image = forms.URLField(required=False, label='URL for Image',
                                      widget=forms.Textarea(
                                          attrs={'rows': 3, 'cols': 55, 'id': 'image_url',
                                                 'placeholder':
                                                     'Images need to be valid URLs to a web-hosted image file.'
                                                 }
                                          )
                                      )

    class Meta:
        model = Avatar
        fields = ('avatar_name',
                  'avatar_description',
                  'avatar_image',
                  'avatar_url_image'
                  )


class DeleteAvatarForm(forms.ModelForm):
    avatar_description = forms.CharField(required=False, label='Description')
    avatar_image = forms.ImageField(required=False)
    avatar_url_image = forms.CharField(required=False, label='URL for Image')

    class Meta:
        model = Avatar
        widgets = {'deleted': forms.RadioSelect}
        fields = ('avatar_name',
                  'avatar_description',
                  'avatar_image',
                  'avatar_url_image',
                  'deleted'
                  )

    def clean(self):
        to_be_deleted = self.cleaned_data.get('deleted')  # , False
        if not to_be_deleted:
            avatar_name = self.cleaned_data.get('avatar_name')  # , None
            if avatar_name in EMPTY_VALUES:
                self.errors['avatar_name'] = self.error_class(['Please enter a name for your Avatar'])
        return self.cleaned_data


class NewPDFForm(forms.ModelForm):
    pdf_name = forms.CharField(required=False, label='name',
                               widget=forms.Textarea(
                                      attrs={'rows': 1, 'cols': 60, 'id': 'pdf_name', 'onkeyup': 'checkForm()',
                                             'placeholder': 'You must give this pdf a name.'
                                             }
                                      )
                               )
    pdf_url = forms.URLField(required=False, label='URL for PDF',
                             widget=forms.Textarea(
                                    attrs={'rows': 3, 'cols': 60, 'id': 'pdf_url', 'onkeyup': 'checkForm()',
                                           'placeholder': 'PDFs need to be valid URLs to a web-hosted file.\r'
                                                          'You can use PDFs from your Google Drive.  '
                                                          'Right click, select "Get shareable link", and paste the '
                                                          'link here.'
                                           }
                                    )
                             )

    class Meta:
        model = PDFCharSheet
        fields = ('pdf_name',
                  'pdf_url'
                  )


class SelectPDF(forms.Form):
    class Meta:
        widgets = {'select_pdf': forms.Select()}
        fields = ('select_pdf', )

    def __init__(self, *args, **kwargs):
        imported_list = kwargs.pop('select_pdf')
        super().__init__(*args, **kwargs)
        self.fields['select_pdf'].choices = imported_list

    select_pdf = forms.ChoiceField(choices=[])

accounts/templates/accounts/about_accounts.html
{% extends 'accounts_base.html' %}

{% block head %}
    <meta charset="UTF-8">
    <title>About Accounts</title>
{% endblock %}


{% block body %}
<br>
<div class="container">
    <p></p>
    <h2>Van Levy Accounts</h2>
    <p>
        This part of the website is dedicated to creating and maintaining your account.
    </p>
    <br>
        {% if user.is_authenticated %}
        <h4>You are logged in as {{user.first_name}}.</h4>
            <br>
            Would you like to:
            <ul>
                <li><a href="{% url 'accounts:view_profile' %}">View or edit your profile</a></li>
                <li><a href="{% url 'accounts:password' %}">Change your password</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
        {% else %}
        <h4>You are not logged in.</h4>
            <br>
            Would you like to:
            <ul>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:password_reset' %}">Reset your password</a></li>
                <li><a href="{% url 'accounts:register' %}">Create a new account</a></li>
            </ul>
        {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts_base.html' %}
{% load static %}

{% block head %}
  <title>Login</title>
  <meta charset="UTF-8" id="my-data"
        data-badlogins="{{ request.session.bad_logins }}"
        data-delay="{{ request.session.delay }}"
        data-badlogintime="{{ request.session.bad_login_time }}"
  >

{% endblock %}

{% block link_account %}
  {% if user.is_authenticated %}
  {% else %}
    <a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a>
  {% endif %}
{% endblock %}

{% block body %}
<div class="container">
  {% if user.is_authenticated %}
    <br>
    <h3>You are logged in with the account: {{user.username}}.</h3>
    <br>
    <p><a href="{% url 'accounts:logout' %}">Logout</a>?</p>
  {% else %}
    {% block required_warning %}
    {% endblock %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-4 col-md-3 col-sm-2 col-xs-12"></div>
        <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
          <div class="container-fluid"
               style="text-align:center; border-radius: 5px; background-color: #f2f2f2; padding: 20px;
                      margin-top: {% block margin %}120px;{% endblock%}">
            <form method="post" id="login">
              {% csrf_token %}
              <table style="width: 100%;">
                <tr><td>
                <input type="text" name="username" id="username" placeholder="Username or email"
                       style="width: 100%; padding: 12px 20px; margin: 8px 0; text-align: center;
                              border: 1px solid #ccc; border-radius: 4px;"
                       autofocus="autofocus">
                </td></tr>
                <tr><td>
                <input type="password" name="password" id="password" placeholder="Password"
                       style="width: 100%; padding: 12px 20px; margin: 8px 0; text-align: center;
                              border: 1px solid #ccc; border-radius: 4px;">
                </td></tr>
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <tr><td>
                        <div class="alert alert-warning" style="margin: 8px 0;">
                          <a class="close" href="#" data-dismiss="alert">×</a>
                          {{ error|escape }}
                        </div>
                      </td></tr>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <tr><td>
                      <div class="alert alert-warning" style="margin: 8px 0;">
                        <a class="close" href="#" data-dismiss="alert">×</a>
                        {{ error }}
                      </div>
                    </td></tr>
                  {% endfor %}
                {% endif %}
                {% if request.session.bad_logins > 3 %}
                  <tr style="display: none;" id="delayAlertRow">
                    <td>
                    <div class="alert alert-danger" style="margin: 8px 0;" id="delayAlert">
                      <a class="close" href="#" data-dismiss="alert">×</a>
                      For security reasons, there will now be a delay of
                        {{ request.session.delay }} seconds
                        before you can login.
                    </div>
                    </td>
                  </tr>
                {% endif %}
                <tr><td>
                  <button type="submit" class="btn btn-primary btn-block" id="submitButton"
                          style="margin: 8px 0px 8px 0px; display: none; padding-bottom: 9px;">
                    <span style="font-size: 1.5em;"><strong>Login</strong></span>
                  </button>
                </td></tr>
              </table>
            </form>
            </div>
            <div class="container-fluid"
                 style="text-align:center; border-radius: 5px; background-color: #f2f2f2; padding: 20px;
                        margin-top: 120px;">
              <p>
                If you do not have an account, please
              </p>
              <a href="{% url 'accounts:register' %}" role="button" class="btn btn-success btn-block">
                <h5 style="margin-bottom: 4px;">Register</h5>
              </a>
            </div>
            <div class="container-fluid"
                 style="text-align:center; border-radius: 5px; background-color: #f2f2f2; padding: 20px;
                        margin-top: 60px;">
              <p>
                If you've forgotten your password,
              </p>
              <a href="{% url 'accounts:password_reset' %}" role="button" class="btn btn-secondary btn-block">
                <h5 style="margin-bottom: 4px;">Reset Password</h5>
              </a>
            </div>
        </div>
        <div class="col-lg-4 col-md-3 col-sm-2 col-xs-12"></div>
      </div>
      <div class="row">
      </div>
    </div>
  {% endif %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
<script>
function showSubmit() {
    document.getElementById('submitButton').style.display='inline';
};
function showDelayAlert() {
    document.getElementById('delayAlertRow').style.display='inline';
};
function showSubmitAndClose() {
    document.getElementById('submitButton').style.display='inline';
    document.getElementById('delayAlertRow').style.display='none';
};
$(function () {
    var bad_logins = $('#my-data').data('badlogins');
    var delay_time = $('#my-data').data('delay');
    var now = new Date();
    var bad_login_str_v1 = $('#my-data').data('badlogintime');
    if (bad_login_str_v1) {
        var bad_login_str = bad_login_str_v1.replace('"', '').replace('"', '');
    };
    var first_bad_login_time = new Date(bad_login_str);
    var clear_bad_login_time =  moment(first_bad_login_time).add(bad_logins, 'm').toDate();
    if ((bad_logins > 3) && (now < clear_bad_login_time)) {
        var delay = delay_time * 1000;
        showDelayAlert();
        setTimeout(showSubmitAndClose, delay);
    } else {
        showSubmit()
    };
});
var $myForm = $("#login");
$myForm.submit(function(){
    $myForm.submit(function(){
        return false;
    });
});
</script>
{% endblock body %}

accounts/templates/accounts/logout.html
{% extends 'accounts_base.html' %}

{% block head %}
  <meta charset="UTF-8">
  <title>Logout</title>
{% endblock %}

{% block body %}
  <div class="container">
    <br>
    <h2>You have logged out.</h2>
    <p>
      Thanks for playing!
    </p>
    <p>
      <a href="{% url 'accounts:login' %}">Log back in?</a>
    </p>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "accounts_base.html" %}
{% load i18n %}

{% block head %}
  <meta charset="UTF-8">
  <title>New Password Confirmed</title>
{% endblock %}

{% block body %}

<div class="container">
  <br>
  {% if user.is_authenticated %}
    <h2>You are logged in as {{user.first_name}}.</h2>
    <br>
    <p><a href="{% url 'accounts:logout' %}">Logout</a>?</p>
  {% else %}
    <h3>Password reset</h3>
    <br>
    <p>
    </p>
      <h3>You have successfully changed your password.</h3>
    <br>
    <p>
      You will need to <a href="{% url 'accounts:login' %}">login</a> with you username and new password.
    </p>
    <br>
  {% endif %}
</div>


{% endblock %}

accounts/templates/accounts/password_success.html
{% extends 'accounts_base.html' %}

{% block head %}
  <meta charset="UTF-8">
  <title>Password Successfully Changed!</title>
{% endblock %}

{% block body %}
<br>
<div class="container" style="text-align: center;">
  <h4>Your password has been successfully changed, {{user}}</h4>
  <p>
    <br>
    <a href="{% url 'accounts:view_profile' %}">
      Click here
    </a>
    to return to your profile.
  </p>
</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'accounts_base.html' %}
{% load static %}

{% block head %}
  <meta charset="UTF-8">
  <title>Registration Form</title>
{% endblock %}

{% block link_logout %}
  {% if user.is_authenticated %}
  {% else %}
    <a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a>
  {% endif %}
{% endblock %}


{% block body %}
<div class="container">
  <br>
  {% if user.is_authenticated %}
    <h3>You are logged in as {{user.first_name}}.</h3>
    <br>
    <p>To create a new account, please <a href="{% url 'accounts:logout' %}">logout</a> and then register.</p>
  {% else %}
    <h3 style="text-align: center;">
      By creating an account, you agree to our <a href="{% url 'vanlevy:terms' %}">terms and conditions.</a>
    </h3>
    <p><br></p>
    <form method="post" id="register">
      {% csrf_token %}
      <table style="margin-left: auto; margin-right: auto;">
        <col style="width: 190px;">
        <col style="width: 325px;">
        <tr style="height: 45px;">
          <td style="padding-left: 5px;">{{ form.username }}</td>
          <td>Usernames must be unique.</td>
        </tr>
        <tr style="height: 45px;">
          <td style="padding-left: 5px;">{{ form.email }}</td>
          <td>One account per email.
            <button type="button" class="btn btn-outline-info btn-sm align-right"
                                  style="border-radius: 10px; padding: 0px 6px;"
                                  tabindex="-1"
                                  onclick="showWhyEmail()" id="showButton">
              ?
            </button>
          </td>
        </tr>
        <tr style="height: 45px;">
          <td style="padding-left: 5px;">{{ form.password1 }}</td>
          <td>Passwords must be at least 8 characters long.</td>
        </tr>
        <tr style="height: 45px;">
          <td style="padding-left: 5px;">{{ form.password2 }}</td>
          <td>Passwords cannot be entirely numeric.</td>
        </tr>
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <tr><td colspan="2">
                <div class="alert alert-warning">
                  <a class="close" href="#" data-dismiss="alert">×</a>
                  {{ error }}
                    {% if error == "This email already has an account." %}
                    <br>You can request a <a href="{% url 'accounts:password_reset' %}">Password Reset</a>.
                    {% endif %}
                </div>
              </td></tr>
            {% endfor %}
          {% endfor %}
        {% endif %}
        <tr style="height: 40px;">
          <td>
            <input type="checkbox" class="align-right" value="agree" id="agree" style="margin-right: 10px;">
          </td>
          <td>I agree to the <a href="{% url 'vanlevy:terms' %}">terms and conditions</a>.</td>
        </tr>
        <tr style="height: 50px;">
          <td style="padding-right: 10px;">
            <button type="submit" class="btn btn-outline-primary align-right" id="submit_button"
                    style="display: none;">
              Register
            </button>
          </td>
          <td></td>
        </tr>
        <tr><td><br></td><td></td></tr>
        <tr>
          <td colspan="2">
            <h4>Account Requirements</h4>
            <ul>
              <li>Your password can't be too similar to your other personal information.</li>
              <li>Your password can't be a commonly used password.</li>
              <li>Usernames can only be 100 characters or fewer.</li>
              <li>Usernames can only contain letters, numbers, or @ + - _ ,</li>
            </ul>
          </td>
        </tr>
        <tr><td><br></td><td></td></tr>
        <tr style="height: 45px;">
          <td colspan="2" style="padding-left: 5px;">
            <div id="whyEmail" style="display: none;">
              <button type="button" class="btn btn-outline-danger btn-sm align-right"
                                    style="border-radius: 10px; padding: 0px 6px;"
                                    onclick="hideWhyEmail()">
                X
              </button>
              <h5>Why is an email required?</h5>
              We only use your email address to contact you if you need to reset your password,
              or if there are other problems with your account.<br><br>
              To learn more, please see our <a href="{% url 'vanlevy:terms' %}">terms and conditions</a>.
            </div>
          </td>
        </tr>
      </table>
    </form>
  {% endif %}
</div>

<script>
var $myForm = $("#register");
$myForm.submit(function(){
  $myForm.submit(function(){
    return false;
  });
});
$("#agree").click(function () {
  var button = $("#submit_button");
  if (document.getElementById('agree').checked) {
    button.show();
  } else {
    button.hide();
  };
});
</script>
<script src="{% static 'vanlevy/files/js/accounts.js'%}"></script>
{% endblock %}