accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

from . import views

app_name = 'accounts'


urlpatterns = [
    path('', views.about, name='about'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('login_required/', LoginView.as_view(template_name='accounts/login_required.html'), name='login_required'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    path('register/', views.register, name='register'),
    path('register/success/', views.register_success, name='register_success'),
    path('profile/', views.view_profile, name='view_profile'),
    # path('profile/<int:other_user_id>/', views.view_profile_other, name='view_profile_other'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    path('profile/create_avatar/', views.edit_avatar, name='create_avatar'),
    path('profile/delete_avatar/<int:avatar_id>', views.edit_avatar, name='delete_avatar'),
    path('profile/edit_avatar/<int:avatar_id>', views.edit_avatar, name='edit_avatar'),

    path('profile/view_avatar/<int:avatar_id>', views.ViewAvatar.as_view()
         , name='view_avatar'),

    path('profile/pdf_charsheets/', views.ViewPDFChars.as_view(), name='pdf_charsheets'),

    path('profile/password/', views.change_password, name='password'),
    path('profile/password/success/', views.change_password_success, name='password_success'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                   success_url='done/',
                                   email_template_name='accounts/password_reset_email.html'
                                   ),
         name='password_reset'
         ),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(success_url='../../../complete/',
                                          template_name='accounts/password_reset_confirm.html',
                                          ),
         name='password_reset_confirm'
         ),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'
         )

]

swdice/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views

app_name = 'swdice'


urlpatterns = [
    path('', views.about, name='about'),

    path('bad_room',
         views.BadRoom.as_view(template_name="swdice/bad_room.html"), name='bad_room'),

    path('enter_with_passcode/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode'),
    path('enter_with_passcode/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/enter_with_passcode.html"), name='enter_passcode_room'),
    path('dockingbay/',
         views.HubView.as_view(template_name="swdice/hub_dockingbay.html"), name='dockingbay'),
    path('switch_avatar/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar'),
    path('switch_avatar/room/<int:swroom_id>/',
         views.HubView.as_view(template_name="swdice/switch_avatar.html"), name='switch_avatar_room'),

    path('room/<int:swroom_id>/',
         views.SWRoomViews.as_view(template_name="swdice/room_sw.html"), name='swroom'),
    path('room/<int:swroom_id>/info',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info.html"), name='swroom_info'),
    path('room/<int:swroom_id>/player-info/<int:player_id>',
         views.SWRoomViews.as_view(template_name="swdice/room_sw_info_player.html"), name='swroom_player_info'),

    path('room/<int:swroom_id>/direct/<slug:slug>',
         views.DirectLink.as_view(template_name="swdice/room_sw_link_direct"), name='room_sw_link_direct'),

    path('makeroom/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_make.html'), name='make_swroom'),
    path('change_passcode/<int:swroom_id>/',
         views.MakeDiceRoom.as_view(template_name='swdice/room_sw_passcode_change.html'), name='change_passcode'),

    path('404', views.error, name='404'),
]

handler404 = views.error

vanlevy/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404

from . import views


app_name = 'vanlevy'

urlpatterns = [
    path('', views.vl_home_view, name='blank'),
    path('home/', views.vl_home_view, name='home'),
    path('about/', views.vl_about_view, name='vl_about'),
    path('resources/', views.vl_resources_view, name='resources'),
    path('cool-stuff/', views.vl_cool_stuff_view, name='cool_stuff'),
    path('dice-rollers/', views.vl_dice_rollers_view, name='dice_rollers'),
    path('portal/', views.personal_portal, name='portal'),
    path('terms/', views.vl_terms_view, name='terms'),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('404/', views.vl_error, name='404'),
    path('kobolds/', views.kobolds_about_view, name='kobolds_about'),
    path('kobolds/terms/', views.kobolds_terms_view, name='kobolds_terms'),
    path('kobolds/privacy/', views.kobolds_privacy_view, name='kobolds_privacy'),
]

handler404 = views.vl_error

swdice/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView, TemplateView, View
from django.views.generic.edit import FormMixin

from accounts.models import VanLevyUser, Avatar
from .models import SWRoomToUser, SWRoomChat, SWRoom, SWRoomDestiny, SWDicePool
from .forms import Make_SW_Room, Enter_SW_Room, Enter_SW_Direct, SW_Room_Chat_Form, SW_Dice_Roll
from .dice import *
from .mixins import AjaxFormMixin

import datetime


# Methods used in views

def make_user_room_link(room_id, user_id, gm=False, banned=False, avatar_is_user=True, avatar=0):
    if SWRoomToUser.objects.filter(user_id_id=user_id, room_id_id=room_id):
        link_instance = SWRoomToUser.objects.filter(user_id_id=user_id, room_id_id=room_id)[0]
        new_user = False
    else:
        link_instance = SWRoomToUser()
        new_user = True
    now = datetime.datetime.now()
    link_instance.room_id_id = room_id
    link_instance.user_id = VanLevyUser(pk=user_id)
    link_instance.admitted = True
    link_instance.game_master = gm
    link_instance.banned = banned
    link_instance.default_avatar_is_user = avatar_is_user

    if new_user:
        link_instance.date_link_created = now
        link_instance.date_admitted = now

    if int(avatar) == 0:
        link_instance.avatar_id_id = ""
    else:
        link_instance.avatar_id_id = int(avatar)

    if gm:
        link_instance.date_made_gm = now
    if banned:
        link_instance.date_banned = now

    link_instance.save()


def save_dice_pool(user, avatar, room, image_url, caption="",
                   num_boost_dice=0, num_ability_dice=0, num_proficiency_dice=0,
                   num_setback_dice=0, num_difficulty_dice=0, num_challenge_dice=0, num_force_dice=0,
                   additional_triumph=0, additional_despair=0, additional_success=0, additional_failure=0,
                   additional_advantage=0, additional_threat=0,
                   additional_light_pips=0, additional_dark_pips=0,
                   num_numerical_dice=0, numerical_dice_sides=0, just_caption=True, secret_roll=False):
    new_dice_pool = SWDicePool()
    new_dice_pool.user = user
    new_dice_pool.avatar = avatar
    new_dice_pool.swroom_id = room
    new_dice_pool.caption = caption
    new_dice_pool.image_url = image_url
    new_dice_pool.num_boost_dice = num_boost_dice
    new_dice_pool.num_ability_dice = num_ability_dice
    new_dice_pool.num_proficiency_dice = num_proficiency_dice
    new_dice_pool.num_setback_dice = num_setback_dice
    new_dice_pool.num_difficulty_dice = num_difficulty_dice
    new_dice_pool.num_challenge_dice = num_challenge_dice
    new_dice_pool.num_force_dice = num_force_dice
    new_dice_pool.additional_triumph = additional_triumph
    new_dice_pool.additional_despair = additional_despair
    new_dice_pool.additional_success = additional_success
    new_dice_pool.additional_failure = additional_failure
    new_dice_pool.additional_advantage = additional_advantage
    new_dice_pool.additional_threat = additional_threat
    new_dice_pool.additional_light_pips = additional_light_pips
    new_dice_pool.additional_dark_pips = additional_dark_pips
    new_dice_pool.num_numerical_dice = num_numerical_dice
    new_dice_pool.numerical_dice_sides = numerical_dice_sides
    new_dice_pool.is_just_caption = just_caption
    new_dice_pool.secret_roll = secret_roll

    swdice = {'boost': num_boost_dice, 'ability': num_ability_dice, 'proficiency': num_proficiency_dice,
              'setback': num_setback_dice, 'difficulty': num_difficulty_dice, 'challenge': num_challenge_dice,
              'force': num_force_dice,
              "additional_triumph": additional_triumph, "additional_despair": additional_despair,
              "additional_success": additional_success, "additional_failure": additional_failure,
              "additional_advantage": additional_advantage, "additional_threat": additional_threat,
              "additional_light_pips": additional_light_pips, "additional_dark_pips": additional_dark_pips,
              }

    summary_string, net_results = roll_sw_dice(**swdice)
    new_dice_pool.faces_summary = summary_string
    new_dice_pool.results_triumph = net_results[0]
    new_dice_pool.results_despair = net_results[1]
    new_dice_pool.results_success = net_results[2]
    new_dice_pool.results_failure = net_results[3]
    new_dice_pool.results_advantage = net_results[4]
    new_dice_pool.results_threat = net_results[5]
    new_dice_pool.results_dark_pips = net_results[6]
    new_dice_pool.results_light_pips = net_results[7]
    numerical_meanings = range(1, (numerical_dice_sides + 1))
    numerical_die = Die("Numerical", numerical_meanings, "", True)
    numerical_string, numerical_results = numerical_die.roll(num_numerical_dice)
    new_dice_pool.results_numerical = numerical_string
    sum_results = 0
    for number in net_results:
        sum_results += number
    if sum_results == 0 and not just_caption and num_numerical_dice == 0:
        new_dice_pool.results_cancel = True
    else:
        new_dice_pool.results_cancel = False

    new_dice_pool.save()


def change_destiny(user, avatar, room, image_url, caption="", delta_light=0, delta_dark=0):
    destiny = SWRoomDestiny.objects.get(room_id_id=room)
    light_pips = destiny.light_pips
    dark_pips = destiny.dark_pips
    new_light = light_pips + delta_light
    new_dark = dark_pips + delta_dark
    if new_light >= 0 and new_dark >= 0:
        destiny.light_pips += delta_light
        destiny.dark_pips += delta_dark
        destiny.save()
        kwargs = {"user": user, "avatar": avatar, "room": room, "caption": caption,
                  "image_url": image_url}
        save_dice_pool(**kwargs)
    else:
        pass


def read_chat(chat_form, avatar, swroom_id, current_user, chat_text, image_url):
    recipient_id = chat_form.data['recipient']
    recipient_user = VanLevyUser.objects.filter(id=recipient_id)[0]
    room_user_link_recipient = SWRoomToUser.objects.filter(room_id_id=swroom_id, user_id=recipient_user)[0]
    recipient_avatar = room_user_link_recipient.avatar_id
    is_private = not (recipient_user == current_user)
    new_chat = SWRoomChat()
    new_chat.room_id_id = swroom_id
    new_chat.chat_text = chat_text
    new_chat.user = current_user
    new_chat.avatar = avatar
    new_chat.image_url = image_url
    new_chat.is_private = is_private
    new_chat.recipient = recipient_user if is_private else None
    new_chat.recipient_avatar = recipient_avatar
    return new_chat


def read_dice(dice_form):
    boost_dice = dice_form.cleaned_data['num_boost_dice']
    ability_dice = dice_form.cleaned_data['num_ability_dice']
    proficiency_dice = dice_form.cleaned_data['num_proficiency_dice']
    setback_dice = dice_form.cleaned_data['num_setback_dice']
    difficulty_dice = dice_form.cleaned_data['num_difficulty_dice']
    challenge_dice = dice_form.cleaned_data['num_challenge_dice']
    force_dice = dice_form.cleaned_data['num_force_dice']
    numerical_sides = dice_form.cleaned_data['numerical_dice_sides']
    numerical_dice = dice_form.cleaned_data['num_numerical_dice']
    caption = dice_form.cleaned_data['caption']
    additional_triumph = dice_form.cleaned_data['additional_triumph']
    additional_despair = dice_form.cleaned_data['additional_despair']
    additional_success = dice_form.cleaned_data['additional_success']
    additional_failure = dice_form.cleaned_data['additional_failure']
    additional_advantage = dice_form.cleaned_data['additional_advantage']
    additional_threat = dice_form.cleaned_data['additional_threat']
    additional_light_pips = dice_form.cleaned_data['additional_light_pips']
    additional_dark_pips = dice_form.cleaned_data['additional_dark_pips']
    total_dice = (boost_dice + ability_dice + proficiency_dice + force_dice +
                  setback_dice + difficulty_dice + challenge_dice + numerical_dice +
                  additional_triumph + additional_despair + additional_success + additional_failure +
                  additional_advantage + additional_threat + additional_light_pips + additional_dark_pips
                  )

    if caption or total_dice > 0:
        valid_pool = True
        if total_dice == 0:
            just_caption = True
        else:
            just_caption = False
    else:
        just_caption = False
        valid_pool = False

    dice_pool = {'caption': caption, "total_dice": total_dice,
                 "num_boost_dice": boost_dice, "num_ability_dice": ability_dice,
                 "num_proficiency_dice": proficiency_dice, "num_setback_dice": setback_dice,
                 "num_difficulty_dice": difficulty_dice, "num_challenge_dice": challenge_dice,
                 "num_force_dice": force_dice, "just_caption": just_caption,
                 "num_numerical_dice": numerical_dice, "numerical_dice_sides": numerical_sides,
                 "additional_triumph": additional_triumph, "additional_despair": additional_despair,
                 "additional_success": additional_success, "additional_failure": additional_failure,
                 "additional_advantage": additional_advantage, "additional_threat": additional_threat,
                 "additional_light_pips": additional_light_pips,
                 "additional_dark_pips": additional_dark_pips, "valid_pool": valid_pool,
                 }
    return dice_pool


def get_chat_carryover(request, chat_form, current_user_id):
    chat_text = chat_form.data['chat_text']
    recipient_id = chat_form.data['recipient']
    if chat_text != '':
        request.session['chat_carryover'] = chat_text
    if int(recipient_id) != int(current_user_id):
        request.session['recipient_carryover'] = recipient_id


def get_dice_carryover(request, dice_form):
    if dice_form.is_valid():
        dice_pool = read_dice(dice_form)
        total_dice = dice_pool['total_dice']
        del dice_pool['total_dice']
        valid_pool = dice_pool['valid_pool']

swdice/templates/swdice/room_sw_link_direct.html
{% extends 'swdice/swroom.html' %}

{% block head %}
    <meta charset="UTF-8">
    <title>SW Room</title>
    <slug>{% if room.open_to_all %}open{% else %}{{ room.passcode }}{% endif %}</slug>
{% endblock %}

{% block navbar_space_part_1 %}
<!--exclude space-->
{% endblock %}

{% block brand %}
    {% load static %}
    <a class="navbar-brand" href="{% url 'vanlevy:home' %}">
        <img src="{% static '/vanlevy/images/IconReverse_32.png' %}" alt="Van Levy Icon" height="32" width="32">
    </a>

    <a class="navbar-brand">
        <span class="d-inline-block text-truncate room-name" >
            {{room.name}}
        </span>
    </a>

    <a class="navbar-brand" style="color:white;" href="{% url 'swdice:dockingbay' %}">
        <img src="{% static '/vanlevy/images/droid_background_32.png' %}" alt="SW Dice Roller" height="32" width="32">
        {% block subtitle %}{% endblock %}
    </a>
{% endblock %}

{% block other_navbar_right %}
<a href="{% url 'swdice:swroom_info' room_number %}">
    <img src="{% static '/swdice/RoomInfoSmall_32.png' %}" alt="Room Info" height="32" width="32">
    {% block info_label %}
        <span style="font-size: 0.67em; color: white; margin-right: 10px; margin-left: -5px;">
            Info
        </span>
    {% endblock %}
</a>
<!--<span style="color: white;">Info </span>-->
{% endblock %}


{% block navbar_space_part_2 %}
<!--exclude space-->
{% endblock %}

{% block body %}

{% load static %}
<h3>Redirecting...</h3>

{% endblock %} <!--body-->

swdice/templates/swdice/swroom_info.html
{% extends 'swdice/swroom.html' %}

{% block head %}
    <meta charset="UTF-8">
    <title>SW Room Info</title>
{% endblock %}

{% block brand %}
{% load static %}
    <a class="navbar-brand" href="{% url 'vanlevy:home' %}">
        <img src="{% static '/vanlevy/IconReverse_32.png' %}" alt="Van Levy Icon" height="32" width="32">
    </a>
<span class="d-inline-block text-truncate" style="max-width: 700px; color:white; font-size: 150%; margin-right: 10px;">
    {{room.name}}
</span>
<a class="navbar-brand" style="color:white;" href="{% url 'swdice:dockingbay' %}">
    <img src="{% static '/vanlevy/droid_background_32.png' %}" alt="SW Dice Roller" height="32" width="32">
    {% block subtitle %}{% endblock %}
</a>
<span class="d-inline-block" style="color:white; font-size: 150%;"> Info Page </span>
{% endblock %}

{% block other_navbar_right %}
{% endblock %}

{% load static %}

{% block user_table %}
<div class="container" id="current_users">
    <h5>Player Information Table</h5>
    <table id="users_table" style="100%">
        <tr>
            <th style="width:80px">User <br>Image</th>
            <th style="width:300px">&nbsp<br>Playing as</th>
            <th style="width:80px">Avatar <br>Image</th>
            <th style="width:80px">&nbsp<br>Role</th>
            {% if player_is_gm %}
            <th style="width:180px">Player <br>Info</th>
            {% endif %}
        </tr>
        {% for player in users_in_room %}
        {% if not player.banned or player_is_gm %}
        <tr>
            <td>
                {% if player.user_id.userprofile.user_url_image %}
                    <img src="{{ player.user_id.userprofile.user_url_image }}" width="40">
                {% else %}
                    <em>no image</em>
                {% endif %}
            </td>
            <td>
                <strong>{{ player.user_id.username }}</strong> playing as:
                <strong>
                    {% if player.avatar_id %}{{ player.avatar_id.avatar_name }}{% else %}theirself{% endif %}
                </strong>
            </td>
            <td>
                {% if player.avatar_id %}
                    {% if player.avatar_id.avatar_url_image %}
                        <img src="{{ player.avatar_id.avatar_url_image }}" width="40">
                    {% else %}
                        <em>no image</em>
                    {% endif %}
                {% else %}
                    {% if player.user_id.userprofile.user_url_image %}
                        <img src="{{ player.user_id.userprofile.user_url_image }}" width="40">
                    {% else %}
                        <em>no image</em>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if player.banned %}<em>banned</em>
                {% elif player.game_master %}<strong>GM</strong>
                {% else %}Player
                {% endif %}
            </td>
            {% if player_is_gm %}
            <td>
                <a href="{% url 'swdice:swroom_player_info' room_number player.user_id_id%}">
                <button type="button" class="btn btn-info btn-sm btn-outline-info" name="Player_Info">
                    Player Info
                </button>
                </a>
            </td>
            {% endif %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</div>
{% endblock %}

{% block gm_stuff %}
{% if player_is_gm %}
    <div class="container-fluid" id="gm_message">
        <div class="row">
            <div class="col">
                <h5>GM-only Information:</h5>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-md-6">
                <h6>
                    Room Details

                </h6>
                <ul style="margin-left: -15px; margin-top: -5px">
                    <li><strong>Created on:</strong> {{ room.created_on }}</li>
                    <li><strong>Created by:</strong> {{ room.created_by.username }}</li>
                    <li><strong>Direct Link:</strong>
                        <button type="button" style="padding: 0;margin-left: 10px;"
                                onclick="copyURL(link_{{room.id}})">
                          <img src="{% static '/vanlevy/copy_button_40_clear.png' %}" alt="info" width="20" height="20">
                        </button>
                        <br>
                        <span style="word-wrap: break-word;" id="link_{{room.id}}">
                            www.vanlevy.com{% url 'swdice:swroom' room_number %}direct/{% if room.open_to_all %}open{% else %}{{ room.passcode}}{% endif %}
                        </span>
                    </li>
                    <li>
                        <strong>Room ID:</strong> <u>{{room.id}}</u>
                    </li>
                    {% if not room.open_to_all %}
                    <li><strong>Passcode:</strong>
                        {% if room.passcode %}
                            "{{ room.passcode }}"
                        {% else %}
                            this room's passcode has been left <em>blank</em>.
                        {% endif %}
                    </li>
                    {% else %}
                    <li>This room is <strong>open to all</strong></li>
                    {% endif %}
                </ul>
                {% if not room.disabled %}
                <a href="{% url 'swdice:change_passcode' room_number %}">
                  <button type="button" class="btn btn-sm btn-outline-info" id="changePasscode"
                        style="margin-right: 15px;">
                    {% if not room.open_to_all %}
                        Change Passcode
                    {% else %}
                        Add Passcode
                    {% endif %}
                    <strong>&#12299</strong>
                  </button>
                </a>
                {% endif %}
            </div>
            <div class="col-md-6">
                {% if room.disabled %}
                <h5><span style="color: darkred;">This room has been <strong>archived</strong>.</span></h5>
                <p>
                    No rolls or chats can be made in this room. On the Docking Bay page, this room is only visible on the
                    Archived Rooms tab.
                </p>
                {% else %}
                <p>
                    As GM, you can choose to <em>archive</em> this room.<br>
                    Once a room has been <em>archived</em>, players will not be able to make any more rolls or chats, and
                    the room will only be visible on the Archived Rooms tab on the Docking Bay page.
                </p>
                {% endif %}
                <div class="row no-gutters" id="disable_button" style="padding: 0px 3px">
                    <div class="col-sm-3">
                      {% if room.disabled %}
                        <button type="button" class="btn btn-sm btn-outline-warning" id="restore"
                                onclick="showRestore()">
                        Restore Room?
                        </button>
                        <button type="button" class="btn btn-sm btn-outline-warning" id="cancel_restore"
                                style="display:none" onclick="hideRestore()">
                        Cancel
                        </button>
                      {% else %}
                        <button type="button" class="btn btn-sm btn-outline-danger" id="disable"
                                onclick="showDisable()">
                        Archive Room?
                        </button>
                        <button type="button" class="btn btn-sm btn-outline-danger" id="cancel_disable"
                                style="display:none" onclick="hideDisable()">
                        Cancel
                        </button>
                      {% endif %} <!--archive/restore button -->
                    </div>
                    <div class="col-sm-9">
                        <div class="container-fluid" id="are_you_sure" style="display: none;">
                            {% if room.disabled %}
                                Are you sure you want to RESTORE this room?
                                <form id="restore_form" method="POST">
                                {% csrf_token %}
                                    <button type="submit" class="btn btn-warning" name="restore_real">
                                        <strong>Yes. RESTORE this room.</strong>
                                    </button>
                                </form>
                            {% else %}
                                Are you sure you want to ARCHIVE this room?
                                <form id="archive_form" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger" name="archive_real">
                                        <strong>Yes. ARCHIVE this room..</strong>
                                    </button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

{% block room_header %}
<div class="container-fluid" style="background-color: #B5D4EF">
    <h4>This page does not automatically update.</h4>
    <p>You must manually refresh to see changes to destiny, new rolls, or new chats.</p>
    <p>
        However, this page loads <em>all</em> actions and chats, while the main page shows only the 100 most
        recent actions and 100 most recent chats.
    </p>
    <a href="{% url 'swdice:swroom' room_number %}">
    <button type="button" class="btn btn-info align-right" name="back to page">
        <strong>&#12298</strong> Back to Live Page
    </button>
    </a>
</div>
{% endblock %}

{% block form_inputs %}
<!-- remove inputs, destiny, and standard user information space -->
{% endblock %}

{% block alt_destiny %}
    <div class="container-fluid" id="destiny_area">
        <h5>Current Destiny</h5>
        <table id="destiny_table">
            <tr>
                <td>
                    <span class="container-fluid" id="destiny_box">
                    {% if dark_pips == 0  and light_pips == 0 %}
                    There are no Destiny Points
                    {% endif %}
                    {% for i in dark_pips|get_range %}
                        <img src="{% static 'swdice/Pips/black.png' %}" width="40" title="Use Dark">
                    {% endfor %}
                    {% for i in light_pips|get_range %}
                        <img src="{% static 'swdice/Pips/white.png' %}" width="40" title="Use Light">
                    {% endfor %}
                    </span>
                </td>
            </tr>
        </table>
    </div>
{% endblock %}
{% block actions_header %}
<hr>
<h5>Actions</h5>
{% endblock %}

{% block alt_chat_header %}
<hr>
<h5>Chats</h5>
{% endblock %}
{% block glossary %}
<!-- hide glossary -->
{% endblock%}
<!-- include block chat_log -->


{% block page_scripts %}
<script>
function showRestore() {
    document.getElementById('restore').style.display='none';
    document.getElementById('cancel_restore').style.display='block';
    document.getElementById('are_you_sure').style.display='block';
}
function hideRestore() {
    document.getElementById('restore').style.display='block';
    document.getElementById('cancel_restore').style.display='none';
    document.getElementById('are_you_sure').style.display='none';
}
function showDisable() {
    document.getElementById('disable').style.display='none';
    document.getElementById('cancel_disable').style.display='block';
    document.getElementById('are_you_sure').style.display='block';
}
function hideDisable() {
    document.getElementById('disable').style.display='block';
    document.getElementById('cancel_disable').style.display='none';
    document.getElementById('are_you_sure').style.display='none';
}
function copyTextToClipboard(text) {
  var textArea = document.createElement("textarea");

  // Place in top-left corner of screen regardless of scroll position.
  textArea.style.position = 'fixed';
  textArea.style.top = 0;
  textArea.style.left = 0;

  // Ensure it has a small width & height. Setting to 1px / 1em doesn't work as this gives a negative w/h on some browsers.
  textArea.style.width = '2em';
  textArea.style.height = '2em';

  // We don't need padding, reducing the size if it does flash render.
  textArea.style.padding = 0;

  // Clean up any borders.
  textArea.style.border = 'none';
  textArea.style.outline = 'none';
  textArea.style.boxShadow = 'none';

  // Avoid flash of white box if rendered for any reason.
  textArea.style.background = 'transparent';

  textArea.value = text;

  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();

  try {
    var successful = document.execCommand('copy');
    var msg = successful ? 'successful' : 'unsuccessful';
    console.log('Copying text command was ' + msg);
  } catch (err) {
    console.log('Oops, unable to copy');
  }

  document.body.removeChild(textArea);
}

function copyURL(element){
    console.log(element.innerText);
    var copyText = element.innerText;
    copyTextToClipboard(copyText)
    var msg = (copyText).concat(" copied to clipboard.")
    alert(msg);
}
</script>
{% endblock %}